Brand.destroy_all
new_balance = Brand.create!(name: 'New Balance')
nike        = Brand.create!(name: 'Nike')
adidas      = Brand.create!(name: 'Adidas')
puma        = Brand.create!(name: 'Puma')
fila        = Brand.create!(name: 'Fila')
asics       = Brand.create!(name: 'ASICS')

Product.destroy_all
Product.create!(name: 'New Balance 1', price: 10.5, sku: 'MX608V4', brand: new_balance)
Product.create!(name: 'New Balance 2', price: 12.5, sku: 'MX608V4', brand: new_balance)
Product.create!(name: 'New Balance 3', price: 14.5, sku: 'MX608V4', brand: new_balance)
Product.create!(name: 'New Balance 4', price: 16.5, sku: 'MX608V4', brand: new_balance)
Product.create!(name: 'New Balance 5', price: 18.5, sku: 'MX608V4', brand: new_balance)
Product.create!(name: 'Nike 1',        price: 20.5, sku: 'MX608V4', brand: nike)
Product.create!(name: 'Nike 2',        price: 22.5, sku: 'MX608V4', brand: nike)
Product.create!(name: 'Nike 3',        price: 24.5, sku: 'MX608V4', brand: nike)
Product.create!(name: 'Nike 4',        price: 26.5, sku: 'MX608V4', brand: nike)
Product.create!(name: 'Nike 5',        price: 28.5, sku: 'MX608V4', brand: nike)
Product.create!(name: 'Adidas 1',      price: 30.5, sku: 'MX608V4', brand: adidas)
Product.create!(name: 'Adidas 2',      price: 32.5, sku: 'MX608V4', brand: adidas)
Product.create!(name: 'Adidas 3',      price: 34.5, sku: 'MX608V4', brand: adidas)
Product.create!(name: 'Adidas 4',      price: 36.5, sku: 'MX608V4', brand: adidas)
Product.create!(name: 'Adidas 5',      price: 38.5, sku: 'MX608V4', brand: adidas)
Product.create!(name: 'Puma 1',        price: 40.5, sku: 'MX608V4', brand: puma)
Product.create!(name: 'Puma 2',        price: 39.5, sku: 'MX608V4', brand: puma)
Product.create!(name: 'Puma 3',        price: 37.5, sku: 'MX608V4', brand: puma)
Product.create!(name: 'Puma 4',        price: 35.5, sku: 'MX608V4', brand: puma)
Product.create!(name: 'Puma 5',        price: 33.5, sku: 'MX608V4', brand: puma)
Product.create!(name: 'Fila 1',        price: 31.5, sku: 'MX608V4', brand: fila)
Product.create!(name: 'Fila 2',        price: 29.5, sku: 'MX608V4', brand: fila)
Product.create!(name: 'Fila 3',        price: 28.5, sku: 'MX608V4', brand: fila)
Product.create!(name: 'Fila 4',        price: 27.5, sku: 'MX608V4', brand: fila)
Product.create!(name: 'Fila 5',        price: 25.5, sku: 'MX608V4', brand: fila)
Product.create!(name: 'ASICS 1',       price: 23.5, sku: 'MX608V4', brand: asics)
Product.create!(name: 'ASICS 2',       price: 21.5, sku: 'MX608V4', brand: asics)
Product.create!(name: 'ASICS 3',       price: 19.5, sku: 'MX608V4', brand: asics)
Product.create!(name: 'ASICS 4',       price: 17.5, sku: 'MX608V4', brand: asics)
Product.create!(name: 'ASICS 5',       price: 15.5, sku: 'MX608V4', brand: asics)